name: urlshort

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  db:
    image: postgres
    restart: always
    shm_size: 1g
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

volumes:
  pgdata:
